##Clock signal
set_property -dict {PACKAGE_PIN K17 IOSTANDARD LVCMOS33} [get_ports clk125]
create_clock -period 8.000 -name sys_clk_pin -waveform {0.000 4.000} -add [get_ports clk125]


##Switches
#set_property -dict { PACKAGE_PIN G15   IOSTANDARD LVCMOS33 } [get_ports { sw[0] }]; #IO_L19N_T3_VREF_35 Sch=sw[0]
#set_property -dict { PACKAGE_PIN P15   IOSTANDARD LVCMOS33 } [get_ports { sw[1] }]; #IO_L24P_T3_34 Sch=sw[1]
#set_property -dict { PACKAGE_PIN W13   IOSTANDARD LVCMOS33 } [get_ports { sw[2] }]; #IO_L4N_T0_34 Sch=sw[2]
#set_property -dict { PACKAGE_PIN T16   IOSTANDARD LVCMOS33 } [get_ports { sw[3] }]; #IO_L9P_T1_DQS_34 Sch=sw[3]


##Buttons
#set_property -dict { PACKAGE_PIN K18   IOSTANDARD LVCMOS33 } [get_ports { reset_pb }]; #IO_L12N_T1_MRCC_35 Sch=btn[0]
#set_property -dict { PACKAGE_PIN P16   IOSTANDARD LVCMOS33 } [get_ports { btn1 }]; #IO_L24N_T3_34 Sch=btn[1]
#set_property -dict { PACKAGE_PIN K19   IOSTANDARD LVCMOS33 } [get_ports { btn[2] }]; #IO_L10P_T1_AD11P_35 Sch=btn[2]
#set_property -dict { PACKAGE_PIN Y16   IOSTANDARD LVCMOS33 } [get_ports { btn[3] }]; #IO_L7P_T1_34 Sch=btn[3]


##LEDs
#set_property -dict { PACKAGE_PIN M14   IOSTANDARD LVCMOS33 } [get_ports { leds[0] }]; #IO_L23P_T3_35 Sch=led[0]
#set_property -dict { PACKAGE_PIN M15   IOSTANDARD LVCMOS33 } [get_ports { leds[1] }]; #IO_L23N_T3_35 Sch=led[1]
#set_property -dict { PACKAGE_PIN G14   IOSTANDARD LVCMOS33 } [get_ports { leds[2] }]; #IO_0_35 Sch=led[2]
#set_property -dict { PACKAGE_PIN D18   IOSTANDARD LVCMOS33 } [get_ports { leds[3] }]; #IO_L3N_T0_DQS_AD1N_35 Sch=led[3]

##Audio Codec
set_property -dict {PACKAGE_PIN R19 IOSTANDARD LVCMOS33} [get_ports bclk]
set_property -dict {PACKAGE_PIN R17 IOSTANDARD LVCMOS33} [get_ports mclk]
set_property -dict {PACKAGE_PIN P18 IOSTANDARD LVCMOS33} [get_ports ac_muten]
set_property -dict {PACKAGE_PIN R18 IOSTANDARD LVCMOS33} [get_ports sdata]
set_property -dict {PACKAGE_PIN T19 IOSTANDARD LVCMOS33} [get_ports lrck]
#set_property -dict { PACKAGE_PIN R16   IOSTANDARD LVCMOS33 } [get_ports { ac_recdat }]; #IO_L19P_T3_34 Sch=ac_recdat
#set_property -dict { PACKAGE_PIN Y18   IOSTANDARD LVCMOS33 } [get_ports { ac_reclrc }]; #IO_L17P_T2_34 Sch=ac_reclrc
set_property -dict {PACKAGE_PIN N18 IOSTANDARD LVCMOS33} [get_ports IIC_0_scl_io]
set_property -dict {PACKAGE_PIN N17 IOSTANDARD LVCMOS33} [get_ports IIC_0_sda_io]


set_property -dict { PACKAGE_PIN W16   IOSTANDARD LVCMOS33 } [get_ports { UART_1_0_txd }]; #IO_L18N_T2_34 Sch=je[2]
set_property -dict { PACKAGE_PIN J15   IOSTANDARD LVCMOS33 } [get_ports { UART_1_0_rxd }]; #IO_25_35 Sch=je[3]

set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[34]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[33]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[35]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[44]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[27]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[32]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[36]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[38]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[43]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[45]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[39]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[40]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[47]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[46]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[37]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[42]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[41]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2Q_data_o[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[30]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[4]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[10]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[15]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[44]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[19]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[24]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[29]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[34]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[42]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[37]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[0]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[1]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[35]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[7]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[8]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[11]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[22]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[25]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[32]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[33]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[39]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[12]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[5]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[3]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[9]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[43]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[38]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[13]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[45]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[16]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[47]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[26]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[28]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[31]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[17]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[2]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[6]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[46]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[14]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[18]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[20]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[21]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[40]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[36]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[23]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[41]}]
set_property MARK_DEBUG true [get_nets {design_1_i/full_radio_0/U0/full_radio_v1_0_S00_AXI_inst/filt2I_data_o[27]}]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk125_IBUF]
